config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :evaluations
  get 'welcome/index'

  devise_for :users

  root 'welcome#index'

end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
	belongs_to :movie 
	belongs_to :user
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :evaluations
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :evaluations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  before_action :set_evaluation, only: [:show, :edit, :update, :destroy]

  # GET /evaluations
  # GET /evaluations.json
  def index
    @evaluations = Evaluation.all
  end

  # GET /evaluations/1
  # GET /evaluations/1.json
  def show
  end

  # GET /evaluations/new
  def new
    @evaluation = Evaluation.new
  end

  # GET /evaluations/1/edit
  def edit
  end

  # POST /evaluations
  # POST /evaluations.json
  def create
    @evaluation = current_user.evaluations.build(evaluation_params) 
   # @evaluation.user_id = current_user.id
    respond_to do |format|
      if @evaluation.save
        format.html { redirect_to @evaluation, notice: 'Evaluation was successfully created.' }
        format.json { render :show, status: :created, location: @evaluation }
      else
        format.html { render :new }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluations/1
  # PATCH/PUT /evaluations/1.json
  def update
    respond_to do |format|
      if @evaluation.update(evaluation_params)
        format.html { redirect_to @evaluation, notice: 'Evaluation was successfully updated.' }
        format.json { render :show, status: :ok, location: @evaluation }
      else
        format.html { render :edit }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluations/1
  # DELETE /evaluations/1.json
  def destroy
    @evaluation.destroy
    respond_to do |format|
      format.html { redirect_to evaluations_url, notice: 'Evaluation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluation
      @evaluation = Evaluation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evaluation_params
      params.require(:evaluation).permit(:user_score, :popular_genre, :best_part, :worst_part,:movie_id,:user_id)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:name, :release_date, :synopsis, :genre, :image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/evaluations/_form.html.erb
<%= form_for(@evaluation) do |f| %>
  <% if @evaluation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evaluation.errors.count, "error") %> prohibited this evaluation from being saved:</h2>

      <ul>
      <% @evaluation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_score %><br>
    <%= f.number_field :user_score , min: 0, max:1 %>
  </div>
  <div class="field">
    <%= f.label :popular_genre %><br>
    <%= f.text_field :popular_genre %>
  </div>
  <div class = "field">
  <%= f.select :movie_id, Movie.all.map{|m| [m.name,m.id]} %>
  </div>
  <div class="field">
    <%= f.label :best_part %><br>
    <%= f.text_field :best_part %>
  </div>
  <div class="field">
    <%= f.label :worst_part %><br>
    <%= f.text_field :worst_part %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/evaluations/edit.html.erb
<h1>Editing Evaluation</h1>

<%= render 'form' %>

<%= link_to 'Show', @evaluation %> |
<%= link_to 'Back', evaluations_path %>

app/views/evaluations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Evaluations</h1>

<table>
  <thead>
    <tr>
      <th>User score</th>
      <th>Popular genre</th>
      <th>Best part</th>
      <th>Worst part</th>
      <th> user </th>
      <th> movie </th>
      <th colspan="3"></th>

    </tr>
  </thead>

  <tbody>
    <% @evaluations.each do |evaluation| %>
      <tr>
        <td><%= evaluation.user_score %></td>
        <td><%= evaluation.popular_genre %></td>
        <td><%= evaluation.best_part %></td>
        <td><%= evaluation.worst_part %></td>
        <td><%= evaluation.user_id%></td>
        <td><%= evaluation.movie_id %></td>

        <td><%= link_to 'Show', evaluation %></td>
        <td><%= link_to 'Edit', edit_evaluation_path(evaluation) %></td>
        <td><%= link_to 'Destroy', evaluation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evaluation', new_evaluation_path %>

app/views/evaluations/new.html.erb
<h1>New Evaluation</h1>

<%= render 'form' %>

<%= link_to 'Back', evaluations_path %>

app/views/evaluations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userscore:</strong>
  <%= @evaluation.user_score %>
</p>

<p>
  <strong>Populargenre:</strong>
  <%= @evaluation.popular_genre %>
</p>

<p>
  <strong>Bestpart:</strong>
  <%= @evaluation.best_part %>
</p>

<p>
  <strong>Worstpart:</strong>
  <%= @evaluation.worst_part %>
</p>

<%= link_to 'Edit', edit_evaluation_path(@evaluation) %> |
<%= link_to 'Back', evaluations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieStats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


<p class="navbar-text pull-right">
<% if user_signed_in? %>
hola  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>

  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :release_date %><br>
    <%= f.date_select :release_date %>
  </div>
  <div class="field">
    <%= f.label :synopsis %><br>
    <%= f.text_area :synopsis %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Release Date</th>
      <th>Synopsis</th>
      <th>Genre</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.release_date %></td>
        <td><%= movie.synopsis %></td>
        <td><%= movie.genre %></td>
        <td> <img src= '<%= movie.image %>' width ="50" height ="50"></img></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Releasedate:</strong>
  <%= @movie.release_date %>
</p>

<p>
  <strong>Synopsis:</strong>
  <%= @movie.synopsis %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @movie.genre %>
</p>

<p>
  <strong>Image:</strong>
  <%= @movie.image %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>